#!/usr/bin/env python3
"""
Orkestrator impor: jalankan semua skrip imper secara berurutan,
validasi hasilnya, danhasilkan satu file SQL gabungan.

Aturan validasi (sesuai BRIEF-AI_YGMS.md section4 T1.4):
  - GAGAL SEMUA kalau ada satu baris salah -- tidak ada data masuk setengah.
  - Setiap tahap dicek sebelum lanjut ke tahap berikutnya.

Cara pakai:
  python scripts/import/run_all.py              -> validasi saja (dry run)
  python scripts/import/run_all.py --execute    -> generate SQL ke folder output/
"""

import argparse
import subprocess
import sys
from pathlib import Path

SCRIPTS = [
    ("members", "import_members.py"),
    ("cross", "import_cross.py"),
    ("finance", "import_finance.py"),
    ("events", "import_events.py"),
]

OUTPUT_DIR = Path(__file__).resolve().parent / "output"


def run_script(script_name, mode="report"):
    """Jalankan satu skrip impor, return (success, output)."""
    script_path = Path(__file__).parent / script_name
    result = subprocess.run(
        [sys.executable, str(script_path), "--mode", mode],
        capture_output=True, text=True, encoding="utf-8",
    )
    return result.returncode == 0, result.stdout, result.stderr


def validate_all():
    """Validasi semua data source, return True jika semua valid."""
    print("=" * 60)
    print("VALIDASI DATA SOURCE")
    print("=" * 60)
    all_ok = True
    for name, script in SCRIPTS:
        print(f"\n--- {name} ---")
        ok, stdout, stderr = run_script(script)
        if ok:
            print(stdout)
        else:
            print(f"ERROR: {stderr}", file=sys.stderr)
            all_ok = False
    print("\n" + "=" * 60)
    if all_ok:
        print("SEMUA VALID -- aman untuk di-impor.")
    else:
        print("VALIDASI GAGAL -- perbaiki dulu sebelum impor.")
    print("=" * 60)
    return all_ok


def generate_all():
    """Generate semua SQL ke folder output/."""
    OUTPUT_DIR.mkdir(exist_ok=True)
    print(f"\nOutput folder: {OUTPUT_DIR}")
    for name, script in SCRIPTS:
        out_path = OUTPUT_DIR / f"{name}.sql"
        ok, stdout, stderr = run_script(script, mode="sql")
        if ok:
            out_path.write_text(stdout, encoding="utf-8")
            print(f"  [OK] {name}.sql ({len(stdout):,} bytes)")
        else:
            print(f"  [FAIL] {name}: {stderr}", file=sys.stderr)
            return False
    combined = OUTPUT_DIR / "00_all.sql"
    parts = []
    parts.append(f"-- Generated by run_all.py")
    parts.append(f"-- Sumber: database/ folder")
    parts.append(f"--")
    parts.append(f"-- URUTAN PENTING: members -> cross -> finance -> events")
    parts.append(f"--   (foreign key dependencies)")
    parts.append("")
    for name, _ in SCRIPTS:
        sql_file = OUTPUT_DIR / f"{name}.sql"
        if sql_file.exists():
            parts.append(f"-- ========== {name.upper()} ==========")
            parts.append(sql_file.read_text(encoding="utf-8"))
            parts.append("")
    combined.write_text("\n".join(parts), encoding="utf-8")
    print(f"\n[OK] Combined: 00_all.sql")
    return True


def main():
    parser = argparse.ArgumentParser(description="Orkestrator impor data")
    parser.add_argument("--execute", action="store_true", help="Generate SQL output")
    args = parser.parse_args()

    if args.execute:
        if validate_all():
            generate_all()
        else:
            sys.exit("Impor dibatalkan: validasi gagal.")
    else:
        validate_all()


if __name__ == "__main__":
    main()
